# ==========================================================
# FASTAPI STUDY GUIDE: 09. MIDDLEWARE & CORS
# ==========================================================

# --- WHAT IS MIDDLEWARE? ---
# A middleware is a function that runs BEFORE every request is processed by your route,
# and AFTER every response is generated by your route.
#
# Think of it like a security guard at the entrance of a building:
# 1. Inspects the visitor (the Request) as they enter (e.g., checks headers, logs arrival).
# 2. Lets the visitor go inside (runs the endpoint code).
# 3. Inspects the visitor (the Response) as they leave (e.g., adds security stamps/headers).

# --- WHAT IS CORS? ---
# CORS (Cross-Origin Resource Sharing) is a security mechanism enforced by web browsers.
# By default, a browser running a frontend app at `http://localhost:3000` is BLOCKED 
# from fetching data from a backend running at `http://localhost:8000`.
# To allow this, the backend must return specific CORS headers (like `Access-Control-Allow-Origin`)
# telling the browser: "Yes, I trust this frontend, let it read my data."

import time
import uvicorn
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="FastAPI: Middleware & CORS")

# ==========================================================
# 1. CONFIGURING CORS MIDDLEWARE
# ==========================================================
# List of origins (frontend URLs) that are allowed to make requests to our API.
# During development, we list localhost ports. For production, we list domain names.
origins = [
    "http://localhost:3000",      # React default port
    "http://localhost:5173",      # Vite/Vue default port
    "https://my-app.vercel.app",  # Production frontend URL
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,            # List of allowed origins
    allow_credentials=True,           # Allow cookies/session headers
    allow_methods=["*"],              # Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
    allow_headers=["*"],              # Allow all headers
)


# ==========================================================
# 2. WRITING A CUSTOM MIDDLEWARE
# ==========================================================
# We define a custom HTTP middleware that:
# 1. Starts a timer.
# 2. Passes the request to the endpoint.
# 3. Measures the time taken to complete.
# 4. Appends a custom header `X-Process-Time` to the response.
# 5. Prints request log to the terminal.
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    # --- BEFORE REQUEST ---
    start_time = time.time()
    
    # Run the endpoint function and get the response
    # (call_next is a function that routes the request to its destination)
    response = await call_next(request)
    
    # --- AFTER REQUEST (BEFORE RESPONSE) ---
    process_time = time.time() - start_time
    
    # Add a custom header to the outgoing HTTP response
    response.headers["X-Process-Time"] = f"{process_time:.4f} seconds"
    
    # Print custom logs to terminal
    print(f"[Log] Request: {request.method} {request.url.path} | Time taken: {process_time:.4f}s")
    
    return response


# ==========================================================
# 3. DEMO ROUTE
# ==========================================================
@app.get("/")
async def root():
    return {"message": "Hello! Open your browser DevTools network tab to check response headers!"}

@app.get("/slow-endpoint")
async def slow():
    # Simulate a slow process
    time.sleep(0.5)
    return {"message": "Sorry to keep you waiting!"}


# --- QUICK SUMMARY FOR RETESTING ---
# 1. Run this file: `python 09_middleware_cors.py`
# 2. Go to: http://127.0.0.1:8000/docs
# 3. Try executing the GET `/slow-endpoint` endpoint.
# 4. Check your Python terminal! You will see:
#    `[Log] Request: GET /slow-endpoint | Time taken: 0.5012s`
# 5. Open your web browser's developer tools (F12) -> Network tab, run the request, and click on it.
#    Look at the "Response Headers": you will find `x-process-time` listed there!

if __name__ == "__main__":
    uvicorn.run("09_middleware_cors:app", host="127.0.0.1", port=8000, reload=True)
